name: frontend
description: "NeuroTechUSC BCI Project UIUX"

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  time: ^2.1.5
  csv: ^6.0.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  http: ^1.3.0
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  flutter_svg: ^2.0.17
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Good coding practices
  flutter_lints: ^5.0.0

# Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - png_assets/background.png
    - png_assets/logo.png
    - png_assets/header.png
    - png_assets/headerText.png
