# NEUROTECHUSC BCI UI/UX
# Dart CI/CD Workflow for GitHub Actions
# Asher Holtham, Mar 2, 2025

name: Flutter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: master # Use the master channel for a newer Flutter version with Dart >= 3.6.1

      - name: Install dependencies
        working-directory: stroop
        run: flutter pub get

      - name: Analyze project source
        working-directory: stroop
        run: flutter analyze

      - name: Run tests
        working-directory: stroop
        run: flutter test
